export const POST_USER = 'POST_USER';
export const POST_USER_SUCCEEDED = 'POST_USER_SUCCEEDED';
export const POST_USER_FAILED = 'POST_USER_FAILED';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCEEDED = 'GET_USER_SUCCEEDED';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const GET_USER_BY_TOKEN = 'GET_USER_BY_TOKEN';
export const GET_USER_BY_TOKEN_SUCCEEDED = 'GET_USER_BY_TOKEN_SUCCEEDED';
export const GET_USER_BY_TOKEN_FAILED = 'GET_USER_BY_TOKEN_FAILED';

export const USER_LOGOUTED = 'USER_LOGOUTED';
export const USER_LOGOUTED_SUCCEEDED = 'USER_LOGOUTED_SUCCEEDED';

export const rest = 'http://localhost:8000/api';