export const GET_FEED = 'GET_FEED';
export const GET_FEED_SUCCEEDED = 'GET_FEED_SUCCEEDED';
export const GET_FEED_FAILED = 'GET_FEED_FAILED';

export const POST_USER = 'POST_USER';
export const POST_USER_SUCCEEDED = 'POST_USER_SUCCEEDED';
export const POST_USER_FAILED = 'POST_USER_FAILED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCEEDED = 'DELETE_USER_SUCCEEDED';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCEEDED = 'GET_USER_SUCCEEDED';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const GET_USER_BY_TOKEN = 'GET_USER_BY_TOKEN';
export const GET_USER_BY_TOKEN_SUCCEEDED = 'GET_USER_BY_TOKEN_SUCCEEDED';
export const GET_USER_BY_TOKEN_FAILED = 'GET_USER_BY_TOKEN_FAILED';

export const GET_OUTER_USER_BY_ID = 'GET_OUTER_USER_BY_ID';
export const GET_OUTER_USER_BY_ID_SUCCEEDED = 'GET_OUTER_USER_BY_ID_SUCCEEDED';
export const GET_OUTER_USER_BY_ID_FAILED = 'GET_OUTER_USER_BY_ID_FAILED';

export const PUT_USER = 'PUT_USER';
export const PUT_USER_SUCCEEDED = 'PUT_USER_SUCCEEDED';
export const PUT_USER_FAILED = 'PUT_USER_FAILED';

export const USER_LOGOUTED = 'USER_LOGOUTED';
export const USER_LOGOUTED_SUCCEEDED = 'USER_LOGOUTED_SUCCEEDED';

export const PUT_AVATAR = 'PUT_AVATAR';
export const PUT_AVATAR_SUCCEEDED = 'PUT_AVATAR_SUCCEEDED';
export const PUT_AVATAR_FAILED = 'PUT_AVATAR_FAILED';

export const DELETE_AVATAR = 'DELETE_AVATAR';
export const DELETE_AVATAR_SUCCEEDED = 'DELETE_AVATAR_SUCCEEDED';
export const DELETE_AVATAR_FAILED = 'DELETE_AVATAR_FAILED';

export const POST_ARTICLE = 'POST_ARTICLE';
export const POST_ARTICLE_SUCCEEDED = 'POST_ARTICLE_SUCCEEDED';
export const POST_ARTICLE_FAILED = 'POST_ARTICLE_FAILED';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCEEDED = 'DELETE_ARTICLE_SUCCEDED';
export const DELETE_ARTICLE_FAILED = 'DELETE_ARTICLE_FAILED';

export const FETCHING = 'FETCHING';
export const FETCHING_CHANGED = 'FETCHING_CHANGED';

export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const ADD_SUBSCRIPTION_SUCCEEDED = 'ADD_SUBSCRIPTION_SUCCEEDED';
export const ADD_SUBSCRIPTION_FAILED = 'ADD_SUBSCRIPTION_FAILED';

export const REMOVE_SUBSCRIPTION = 'REMOVE_SUBSCRIPTION';
export const REMOVE_SUBSCRIPTION_SUCCEEDED = 'REMOVE_SUBSCRIPTION_SUCCEEDED';
export const REMOVE_SUBSCRIPTION_FAILED = 'REMOVE_SUBSCRIPTION_FAILED';

export const FEED_IS_INCOMING = 'FEED_IS_INCOMING';
export const FEED_IS_INCOMING_CHANGED = 'FEED_IS_INCOMING_CHANGED';

export const GET_OUTER_USER = 'GET_OUTER_USER';
export const GET_OUTER_USER_SUCCEEDED = 'GET_OUTER_USER_SUCCEEDED';
export const GET_OUTER_USER_FAILED = 'GET_OUTER_USER_FAILED';

export const CLEAR_OUTER_USER = 'CLEAR_OUTER_USER';
export const CLEAR_OUTER_USER_SUCCEEDED = 'CLEAR_OUTER_USER_SUCCEEDED';

export const socketServer = 'ws://localhost:8080';
export const rest = 'http://localhost:8000/api';
export const fileServer = 'http://localhost:8000';
export const localServer = 'http://localhost:3000'


export const usernameRegexp = /[a-z]{1,1}[\w]{3,}/;
export const passwordRegexp = /[a-z0-9]{4,}/;